### ISSUE TITLE
Null Eth Address display options

### ISSUE THREAD

**Issue by thelifeandtimes** [tocwex/fund#95] opened 2024-07-04 19:54 UTC
Right now during the 'draft' and 'proposed' stages, the role cards will display `0x00....000` as the ethereum address for a worker or oracle. Really what is happening here is that there is not yet a value for that `@ux`. If this field is null, we should instead display `eth address unavailable`.

**Comment by sidnym-ladrut** [comment] 2024-10-16 15:48
Duplicate of #129.

**Closed as completed by sidnym-ladrut** 2024-10-16 15:48 UTC
Labels: enhancement
